import type { NextPage } from 'next'
import Head from 'next/head'
import { PostCard, Categories, PostWidget } from '../components'

const posts = [
  { title: 'NEXT.js Testing',
    excerpt: 'Learn more...'
  },
  {
    title: 'Modern Blog App with NEXT and Tailwind',
    excerpt: 'Learn more...',
  }
]

const Home: NextPage = () => {
  return (
    <div className="container mx-auto px-10 mb-8 text-gray-100">
      <Head>
        <title> My Personal E-BLOG | Delos-343 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post) =>
              <PostCard post={post} key={post.title} />
          )}
        </div>
        <div className='lg:col-span-4 col-span-1'>
            <div className='lg:sticky relative top-8'>
              <PostWidget />
              <Categories />
            </div>
        </div>
      </div>

    </div>
  )
}

export default Home
